package main

import (
	"encoding/json"
	"fmt"
	"sync"
	"time"
)

// ContractRule is one rule in a TFC template, each traceable to a 약관 article.
// Templates are human-ratified (G4 — LLM never generates rules).
type ContractRule struct {
	ID          string `json:"id"`
	Description string `json:"description"`
	Gate        string `json:"gate"`                    // "L1" | "L2"
	Provenance  string `json:"provenance"`              // "약관 제15조 제1항"
	BoundValue  string `json:"bound_value,omitempty"`   // instance-bound value after TCE
	Active      bool   `json:"active"`
}

// TFC (TPMN Format Contract) is the instance-bound contract for one document.
// Generated by TCE: category template + anchor A instance values.
type TFC struct {
	Category    string            `json:"category"`
	Version     string            `json:"version"`
	Rules       []ContractRule    `json:"rules"`
	BoundValues map[string]any    `json:"bound_values"`
	GeneratedAt string            `json:"generated_at"`
}

// ContractTemplate is the human-ratified category template stored in contractDB.
// Each rule carries 약관 조항 provenance — no rule may be LLM-authored.
type ContractTemplate struct {
	Category string         `json:"category"`
	Version  string         `json:"version"`
	Rules    []ContractRule `json:"rules"`
}

// contractDB is the in-memory Contract DB — MVP has ONE ratified template for 보험금청구서.
// This IS the "HITL 씨앗": a human reviewed and ratified these rules against 약관.
var contractDB = map[string]ContractTemplate{
	"보험금청구서": {
		Category: "보험금청구서",
		Version:  "v1.0-2026-06",
		Rules: []ContractRule{
			{
				ID:          "R1",
				Gate:        "L1",
				Provenance:  "약관 제3조 제1항",
				Description: "피보험자명이 명시되어야 한다",
				Active:      true,
			},
			{
				ID:          "R2",
				Gate:        "L1",
				Provenance:  "약관 제4조 제2항",
				Description: "진단코드(ICD-10)가 유효한 형식이어야 한다",
				Active:      true,
			},
			{
				ID:          "R3",
				Gate:        "L1",
				Provenance:  "약관 제7조 제1항",
				Description: "청구금액이 0보다 크고 약관조항ref가 명시되어야 한다",
				Active:      true,
			},
			{
				ID:          "R4",
				Gate:        "L2",
				Provenance:  "약관 제15조 제1항",
				Description: "승인금액은 약관한도 이내여야 한다",
				Active:      true,
			},
			{
				ID:          "R5",
				Gate:        "L2",
				Provenance:  "약관 제17조 제3항",
				Description: "특약(rider) 추가보장은 특약 가입증명서가 첨부된 경우에만 유효하다",
				Active:      true,
			},
			{
				ID:          "R6",
				Gate:        "L2",
				Provenance:  "약관 제7조 제2항",
				Description: "F의 모든 인용근거는 앵커 A의 필드 또는 evidence_spans으로 역추적 가능해야 한다",
				Active:      true,
			},
			{
				ID:          "R7",
				Gate:        "L2",
				Provenance:  "약관 제8조",
				Description: "승인금액은 청구금액을 초과할 수 없다",
				Active:      true,
			},
		},
	},
}

// hitlRulesMu guards hitlExtraRules.
var hitlRulesMu sync.Mutex

// hitlExtraRules holds rules added via the HITL UI (4막 template edit).
// In-memory only — resets on server restart (MVP).
var hitlExtraRules []ContractRule

// AddHITLRule appends a new rule to the template (HITL 4막 endpoint).
func AddHITLRule(description, provenance, gate string) ContractRule {
	hitlRulesMu.Lock()
	defer hitlRulesMu.Unlock()
	if gate == "" {
		gate = "L2"
	}
	rule := ContractRule{
		ID:          fmt.Sprintf("HITL-%d", len(hitlExtraRules)+1),
		Description: description,
		Gate:        gate,
		Provenance:  provenance + " (HITL 추가)",
		Active:      true,
	}
	hitlExtraRules = append(hitlExtraRules, rule)
	return rule
}

// ClearHITLRules resets HITL additions (demo reset).
func ClearHITLRules() {
	hitlRulesMu.Lock()
	defer hitlRulesMu.Unlock()
	hitlExtraRules = nil
}

// GetHITLRules returns a copy of current HITL rules.
func GetHITLRules() []ContractRule {
	hitlRulesMu.Lock()
	defer hitlRulesMu.Unlock()
	out := make([]ContractRule, len(hitlExtraRules))
	copy(out, hitlExtraRules)
	return out
}

// GetContractTemplate returns the current template + HITL additions for a category.
func GetContractTemplate(category string) ContractTemplate {
	tmpl, ok := contractDB[category]
	if !ok {
		tmpl = contractDB["보험금청구서"]
	}
	hitlRulesMu.Lock()
	extra := make([]ContractRule, len(hitlExtraRules))
	copy(extra, hitlExtraRules)
	hitlRulesMu.Unlock()

	out := ContractTemplate{
		Category: tmpl.Category,
		Version:  tmpl.Version,
		Rules:    append(append([]ContractRule{}, tmpl.Rules...), extra...),
	}
	return out
}

// RunTCE is the TPMN-Contract-Extractor node.
// G4: Templates are human-ratified; TCE only binds instance values, never generates rules.
// Binding: select applicable rules + fill BoundValue from anchor A fields.
func RunTCE(category string, anchorA map[string]any) (*TFC, error) {
	tmpl := GetContractTemplate(category)

	// Deep copy rules for instance binding
	rules := make([]ContractRule, len(tmpl.Rules))
	copy(rules, tmpl.Rules)

	bound := make(map[string]any)

	// Bind 약관한도 → R4
	if v, ok := anchorA["약관한도"]; ok {
		bound["약관한도"] = v
		for i := range rules {
			if rules[i].ID == "R4" {
				rules[i].BoundValue = fmt.Sprintf("약관한도: %v원", v)
			}
		}
	}

	// Bind 약관조항ref
	if v, ok := anchorA["약관조항ref"]; ok {
		bound["약관조항ref"] = v
	}

	// Bind 피보험자명 → R1
	if v, ok := anchorA["피보험자명"]; ok {
		bound["피보험자명"] = v
		for i := range rules {
			if rules[i].ID == "R1" {
				rules[i].BoundValue = fmt.Sprintf("%v", v)
			}
		}
	}

	// Bind 청구금액
	if v, ok := anchorA["청구금액"]; ok {
		bound["청구금액"] = v
	}

	// Bind rider_claims → R5 (key rule for 2막 hero)
	if rc, ok := anchorA["rider_claims"]; ok {
		if claims, ok := rc.([]any); ok && len(claims) > 0 {
			bound["rider_claims"] = claims
			for i := range rules {
				if rules[i].ID == "R5" {
					rules[i].BoundValue = fmt.Sprintf("청구된 특약: %v", claims)
				}
			}
		}
	}

	// Bind attached_docs
	if v, ok := anchorA["attached_docs"]; ok {
		bound["attached_docs"] = v
	}

	return &TFC{
		Category:    tmpl.Category,
		Version:     tmpl.Version,
		Rules:       rules,
		BoundValues: bound,
		GeneratedAt: time.Now().UTC().Format(time.RFC3339),
	}, nil
}

// TFCToJSON serializes TFC for LLM prompts.
func TFCToJSON(tfc *TFC) string {
	b, _ := json.MarshalIndent(tfc, "", "  ")
	return string(b)
}

// TFCPreconditions extracts L1 rules as a string slice for the light gate prompt.
func TFCPreconditions(tfc *TFC) []string {
	var out []string
	for _, r := range tfc.Rules {
		if r.Gate == "L1" && r.Active {
			line := fmt.Sprintf("[%s, %s] %s", r.ID, r.Provenance, r.Description)
			if r.BoundValue != "" {
				line += " (인스턴스 값: " + r.BoundValue + ")"
			}
			out = append(out, line)
		}
	}
	return out
}

// TFCPostconditions extracts L2 rules as a string slice for the epistemic check prompt.
func TFCPostconditions(tfc *TFC) []string {
	var out []string
	for _, r := range tfc.Rules {
		if r.Gate == "L2" && r.Active {
			line := fmt.Sprintf("[%s, %s] %s", r.ID, r.Provenance, r.Description)
			if r.BoundValue != "" {
				line += " (인스턴스 값: " + r.BoundValue + ")"
			}
			out = append(out, line)
		}
	}
	return out
}
